server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.8:8848
    sentinel:
      transport:
        dashboard: 192.168.1.8:8080
        port: 8719
      web-context-unify: false
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.8:8848
            data-id: ${spring.application.name}
            group: DEFAULT_GROUP
            data-type: json
            rule-type: flow