
spring:
  profiles:
    active: prod
  application:
    name: cloud-payment-service
  datasource:
    username: sapiece
    password: 159357
    url: jdbc:mysql://192.168.1.8:3306/db_2024?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sapiece.entities
server:
  port: 8002